[package]
name = "pochtecatl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.12"
fnv = "1.0.7"
log = { version = "0.4.21", features = ["kv_unstable", "std", "serde"] }
serde = { version = "1.0", default_features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default_features = false, features = ["alloc"] }

structured-logger = "1.0.3"
tokio = { version = "1.37.0", features = ["full"] }
lazy_static = "1.4.0"
ruint = "1.12.1"
fraction = "0.15.1"
lru = "0.12.3"
dotenvy = "0.15.7"

alloy = { git = "https://github.com/alloy-rs/alloy", rev = "66fa192", features = [
    # "dyn-abi",
    # "json-abi",
    # "json",
    "sol-types",
    # "rlp",
    # "serde",
    "contract",
    # "consensus",
    # "eips",
    "network",
    # "genesis",
    "node-bindings",
    "providers",
    "rpc",
    # "json-rpc",
    "rpc-client",
    # "rpc-types",
    "rpc-types-eth",
    # "rpc-types-engine",
    "rpc-types-trace",
    "signers",
    # "signer-aws",
    # "signer-gcp",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
    "transports",
    "transport-http",
    "transport-ipc",
    "transport-ws",
    "pubsub",
] }
# Temp dependency fix to enable relevant features - Ref: https://github.com/alloy-rs/examples/pull/3#discussion_r1537842062
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "66fa192", features = [
    "pubsub",
] }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "66fa192", features = [
    "pubsub",
    "ws",
] }

[patch.crates-io]
alloy-core = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
alloy-dyn-abi = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
alloy-json-abi = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
alloy-primitives = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
alloy-sol-macro = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
alloy-sol-types = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
syn-solidity = { git = "https://github.com/alloy-rs/core", rev = "525a233" }
